env:
 - GHCVER=7.8.4 CABALVER=1.22
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy-1.19.4 alex-3.1.3
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$HOME/.cabal/bin:$PATH
 - sudo apt-get update -qq
 - sudo apt-get install -qq zlib1g-dev libncurses-dev libcairo2-dev libglib2.0-dev libpango1.0-dev libgtk2.0-dev libglade2-dev
install:
 - travis_retry cabal update
 - cabal install gtk2hs-buildtools
 - cabal install glade parsec1
 - cabal install --only-dependencies
script:
 - make
 - ./hets -V
 - export HETS_MAGIC=$PWD/magic/hets.magic
 - make check

