sudo: required
dist: trusty
language: generic
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - ./.stack-work
addons:
  apt:
    sources:
      - sourceline: ppa:hets/hets
    packages:
      - libgmp-dev
      - software-properties-common
      - dpkg-dev
      - spass
      - darwin
      - openjdk-7-jdk
matrix:
  include:
    # Default environment:
    - env:
    # Simulate Ubuntu xenial and yakkety (GHC 7.10.3):
    - env: STACK_YAML="$PWD/.stack-ghc-7.10.3.yaml"
    # Simulate Ubuntu artful (GHC 8.0.2):
    - env: STACK_YAML="$PWD/.stack-ghc-8.0.2.yaml"
  allow_failures:
    - env: STACK_YAML="$PWD/.stack-ghc-7.10.3.yaml"
    - env: STACK_YAML="$PWD/.stack-ghc-8.0.2.yaml"

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - sudo apt-get install --no-install-recommends `dpkg-checkbuilddeps debian/control 2>&1 | cut -f3- -d":" | sed -e 's,([^)]*),,g' -e 's,openjdk-.*-jdk,,'` || true
script:
  - make stack
  - stack exec -- ghc -V
  - make
  - ./hets -V
  - export HETS_MAGIC=$PWD/magic/hets.magic
  - make check
