sudo: required
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq zlib1g-dev libncurses-dev libcairo2-dev libglib2.0-dev libpango1.0-dev libgtk2.0-dev libglade2-dev ghc-7.10.2 cabal-install-1.22
 - export PATH=/opt/ghc/7.10.2/bin:/opt/cabal/1.22/bin:$PATH
install:
 - travis_retry cabal update
 - cabal install alex happy
 - cabal install gtk2hs-buildtools
 - cabal install glade parsec1
 - cabal install --only-dependencies
script:
 - make
 - ./hets -V
 - export HETS_MAGIC=$PWD/magic/hets.magic
 - make check

