language: haskell
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq zlib1g-dev libncurses-dev libcairo2-dev libglib2.0-dev libpango1.0-dev libgtk2.0-dev libglade2-dev
install:
 - cabal install http://www.dfki.de/sks/hets/src-distribution/programatica-1.0.0.4.tar.gz
 - cabal install --only-dependencies
