sudo: required
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq zlib1g-dev libncurses-dev libcairo2-dev libglib2.0-dev libpango1.0-dev libgtk2.0-dev libglade2-dev ghc-8.0.1 cabal-install-1.24
 - export PATH=/opt/ghc/8.0.1/bin:/opt/cabal/1.24/bin:$PATH
install:
 - travis_retry cabal update
 - cabal install alex happy
 - cabal install gtk2hs-buildtools
 - git clone https://github.com/cmaeder/glade.git
 - cd glade
 - cabal install
 - cd ..
 - cabal install --only-dependencies
script:
 - make
 - ./hets -V
 - export HETS_MAGIC=$PWD/magic/hets.magic
 - make check
